### ISSUE TITLE
Add Woke as part of our build requirement

### ISSUE THREAD

**Issue by chrispenny** [silverstripe-terraformers/keys-for-cache#24]
https://github.com/get-woke/woke

**Comment by adrhumphreys** [comment]
Had a quick look at woke and it seems like Alex is a better option, there's an issue running it currently: https://github.com/get-alex/alex/issues/325

But aside from that it's a NPM dependency so adding it in and running it on local machines is a lot easier (woke requires running an installer which is just a script but is more effort than running a `npm install`)

**Comment by TheSceneman** [comment]
Alex looks like a goer - are there any working examples of this in place? or should we just add it the json and see how it rolls?

**Comment by chrispenny** [comment]
> are there any working examples of this in place

None that I'm aware of. This would be my first time adding something like this.

**Comment by TheSceneman** [comment]
@chrispenny just wanted to ask a couple of thing before I add any code.

To be clear, the idea of this would be to lint the KFC module using Alex. A passing lint would be required before any PRs are merged. Thats the gist of it? Theres currently no package.json for this repo so will need to be added and linter fired off manually by devs. Then we'd add a note in the readme explaining as such?

Is all this in line with your thoughts? I know this issue is a year old but.

**Comment by chrispenny** [comment]
> A passing lint would be required before any PRs are merged

Yup, that sounds good.

> and linter fired off manually by devs

How do you mean? Can it not be run automatically as part of the pipeline?

I guess if we can't tie it to the pipeline/build/etc, it might still be worth having? I mean, I don't think we necessarily need to be on top of it 100% of the time. Perhaps it's enough that we just manually run/review it every now and then?
